In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/nepal_rainfall_dataset.csv')

In [3]:
df.head()

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
0,1982-04-11,1,900611,NP01,946.0,45.821354,19.132627,69.161736,53.436928,113.801270,92.26596,210.591890,126.909030,122.140650,final
1,1982-04-21,1,900611,NP01,946.0,7.949260,22.579634,66.145874,61.419945,117.160675,109.06899,46.952255,107.115220,107.093680,final
2,1982-05-01,1,900611,NP01,946.0,24.917547,40.198025,78.688160,81.910286,135.640600,145.01720,66.192154,96.292590,93.749650,final
3,1982-05-11,1,900611,NP01,946.0,34.821354,35.410430,67.688156,98.188090,162.882660,174.10437,98.542270,70.442390,93.734535,final
4,1982-05-21,1,900611,NP01,946.0,37.136364,55.753628,96.875260,131.362090,192.804440,225.67590,69.356125,74.709366,85.749940,final

**Columns of the dataset and what they mean:**


- `date` &#8594; The date of when the record was taken

- `adm_level` &#8594; The adminstrative level of the data, 1 is provincial level and 2 is district level
- `adm_id` &#8594; The numeric ID for the administrative unit
- `PCODE` &#8594; The Place code used by OCHA/UN; is the standard identifier for the dataset
- `n_pixels` &#8594; The number of satellite raster pixels that fall inside the district/province.
- `rfh` &#8594; 10-day rainfall [mm]
- `r1h` &#8594; Rainfall 1-month rolling aggregation [mm]
- `r3h` &#8594; Rainfall 3-month rolling aggregation [mm]
- `rfh_avg` &#8594; Long-term average of 10-day rainfall [mm]
- `r1h_avg` &#8594; Long-term average of 1-month rolling rainfall [mm]
- `r3h_avg` &#8594; Long-term average of 3-month rolling rainfall [mm]
- `rfq` &#8594; 10-day rainfall anomaly [%]
- `r1q` &#8594; 1-month rainfall anomaly [%]
- `r3q` &#8594; 3-month rainfall anomaly [%]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 138264 entries, 0 to 138263
Data columns (total 15 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date       138264 non-null  str
 1   adm_level  138264 non-null  int64
 2   adm_id     138264 non-null  int64
 3   PCODE      138264 non-null  str
 4   n_pixels   138264 non-null  float64
 5   rfh        138264 non-null  float64
 6   rfh_avg    138264 non-null  float64
 7   r1h        138096 non-null  float64
 8   r1h_avg    138096 non-null  float64
 9   r3h        137592 non-null  float64
 10  r3h_avg    137592 non-null  float64
 11  rfq        138264 non-null  float64
 12  r1q        138096 non-null  float64
 13  r3q        137592 non-null  float64
 14  version    138264 non-null  str
dtypes: float64(10), int64(2), str(3)
memory usage: 15.8 MB

In [6]:
df.isna().sum()

date           0
adm_level      0
adm_id         0
PCODE          0
n_pixels       0
rfh            0
rfh_avg        0
r1h          168
r1h_avg      168
r3h          672
r3h_avg      672
rfq            0
r1q          168
r3q          672
version        0
dtype: int64

In [5]:
df.describe()

,adm_level,adm_id,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q
count,138264.000000,1.382640e+05,138264.000000,138264.000000,138264.000000,138096.000000,138096.000000,137592.000000,137592.000000,138264.000000,138096.000000,137592.000000
mean,1.916667,9.990906e+05,129.238095,42.117127,41.346113,126.385766,124.084486,378.788455,371.739901,102.086244,102.375944,102.093613
std,0.276386,2.969192e+04,209.136029,54.642894,46.451158,147.452031,135.676747,373.097342,353.091780,51.110063,41.528713,31.686566
min,1.000000,9.006110e+05,4.000000,0.000000,0.000000,1.000000,1.279235,10.278689,15.860656,9.777309,16.850649,23.278738
25%,2.000000,1.008019e+06,47.750000,4.189189,6.144242,16.279230,20.644444,71.287180,76.367260,72.253065,76.431265,81.413501
50%,2.000000,1.008040e+06,63.000000,15.600000,16.746826,53.750000,50.375397,217.715285,212.757480,93.191585,95.334317,98.161615
75%,2.000000,1.008060e+06,89.250000,64.385936,69.368200,206.529420,208.784380,629.838175,633.159240,115.438163,118.882608,117.093445
max,2.000000,1.008081e+06,1134.000000,665.442600,228.566670,1299.008400,642.758500,2202.672000,1542.910900,1095.980000,546.588000,457.790130

In [7]:
df.columns

Index(['date', 'adm_level', 'adm_id', 'PCODE', 'n_pixels', 'rfh', 'rfh_avg',
       'r1h', 'r1h_avg', 'r3h', 'r3h_avg', 'rfq', 'r1q', 'r3q', 'version'],
      dtype='str')

In [9]:
df.tail()

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
138259,2026-08-01,2,1008081,NP0218,33.0,77.030304,87.607070,390.36362,344.60605,794.39390,765.63740,88.578880,113.08832,103.731520,final
138260,2026-08-11,2,1008081,NP0218,33.0,56.666668,100.518180,236.15152,324.82020,800.84845,829.61310,58.441746,73.11606,96.553535,final
138261,2026-08-21,2,1008081,NP0218,33.0,103.848490,98.134346,237.54547,286.25958,832.45450,875.07170,105.540480,83.27467,95.157530,final
138262,2026-09-01,2,1008081,NP0218,33.0,92.000000,86.648480,252.51515,285.30100,878.21220,909.50000,105.839180,88.70625,96.578700,prelim
138263,2026-09-11,2,1008081,NP0218,33.0,61.333332,77.593940,257.18182,262.37677,883.57580,921.84644,80.312584,98.05707,95.870880,prelim